### ISSUE TITLE
Suite test result cant be found

### ISSUE THREAD

**Issue by DevNiko** [ghost-inspector/node-ghost-inspector#48]
Hi,

when i try to retrieve the suite test result using the nodejs cli, i allway get an "Suite result not found" Error

`npx ghost-inspector suite-result list-test-results 621901987ff0437a6ec95c77`

> 

Error: Suite result not found
    at GhostInspector.request (/home/user/.nvm/versions/node/v14.18.3/lib/node_modules/ghost-inspector/index.js:126:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async GhostInspector.getSuiteResultTestResults (/home/user/.nvm/versions/node/v14.18.3/lib/node_modules/ghost-inspector/index.js:598:19)
    at async Object.handler (/home/user/.nvm/versions/node/v14.18.3/lib/node_modules/ghost-inspector/bin/commands/suite-result/list-test-results.js:26:21)

But i see the result in the run history of the suite in my dashboard.

![gi-suite-test-results](https://user-images.githubusercontent.com/5196588/155752689-004f8be7-37ae-48fa-88a4-caa78c705570.png)

I am using the cli 7.0.0 on Ubuntu 20.04 and Node v14.18.3

**Comment by aaronfay** [comment]
Hey @DevNiko thanks for reporting! I'll try this out right away and see if I can figure out what's going on 🧐

**Comment by aaronfay** [comment]
Hi @DevNiko, we've just published version `7.0.1` that should address this issue, let us know if you have any other issues with it 🙏🏻
